on: 
  workflow_dispatch:
  push:
    branches:
      - adf_publish

name: Data Factory

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Install Poweshell Modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name az.resources
        Install-Module -Name az.datafactory
        Install-Module -Name azure.datafactory.tools

    - name: Deploy Data Factory
      shell: pwsh
      run: Publish-AdfV2FromJson -RootFolder "../demolake/adf" -ResourceGroupName "demolake-dev-rg" -DataFactoryName "demolake-dev-adf" -Location "west europe"
   