on: [workflow_dispatch]
name: Data Factory

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Install Data Factory Tools
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name az.datafactory
        Install-Module -Name azure.datafactory.tools
        Import-Module azure.datafactory.tools
        Publish-AdfV2FromJson -RootFolder "../demolake/adf" -ResourceGroupName "demolake-dev-rg" -DataFactoryName "demolake-dev-adf" -Location "west europe"

