on: [workflow_dispatch]

name: Databricks

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Install Databricks CLI
      shell: pwsh
      run: |
        pip install databricks-cli

    - name: Install Powershell Modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name az.resources
        Install-Module -Name databricksps

    - name: Set Databricks Environment
      env:
        SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      shell: pwsh
      run: |
        $subscriptionid = $env:SUBSCRIPTION_ID
        $resourceGroupName = 'demolake-dev-rg'
        $workspaceName = 'demolake-dev-dbr'
        $azureResourceId = "/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Databricks/workspaces/$workspaceName"

        Set-DatabricksEnvironment -UsingAzContext -AzureResourceID $azureResourceId
        Add-DatabricksWorkspaceDirectory -Path "/admin"
        $env:DATABRICKS_AAD_TOKEN = $(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | ConvertFrom-json | Select-Object -exp accessToken )
        databricks configure --aad-token --host https://adb-5039276063839249.9.azuredatabricks.net
        databricks secrets create-scope --scope keyvault_scope --scope-backend-type AZURE_KEYVAULT --resource-id /subscriptions/83f0ac3f-2fbb-4ae2-9466-9a47162519f7/resourceGroups/demolake-dev-rg/providers/Microsoft.KeyVault/vaults/demolake-dev-kv-iwmt54eo --dns-name https://demolake-dev-kv-iwmt54eo.vault.azure.net/
        databricks secrets list-scopes