on: [workflow_dispatch]

name: Databricks

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Install Powershell Modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name az.resources
        Install-Module -Name databricksps

    - name: Set Databricks Environment
      env:
        SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      shell: pwsh
      run: |
        $subscriptionid = $env:SUBSCRIPTION_ID
        $resourceGroupName = 'demolake-dev-rg'
        $workspaceName = 'demolake-dev-dbr'
        $azureResourceId = "/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Databricks/workspaces/$workspaceName"

        Set-DatabricksEnvironment -UsingAzContext -AzureResourceID $azureResourceId
        Add-DatabricksWorkspaceDirectory -Path "/admin"
        $body = @{application_id= '30d92e31-03d5-4c44-814c-802f1f2602c5'}
        Invoke-DatabricksApiRequest -Method "POST" -EndPoint "/2.0/token-management/on-behalf-of/tokens" -Body $body
