on: 
  workflow_dispatch:
    inputs:
    deploy-target:
      description: 'deploy target'
      required: true
      default: 'dev'
      type: choice
      options:
      - dev
      - tst
      - prd

name: Infrastructure as Code

run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Bicep Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ../demolake/deploy/infra/main.bicep
        failOnStdErr: false

  deploy-infra-tst:
    if: ${{ github.event.inputs.deploy-target == 'tst' || github.event.inputs.deploy-target == 'prd' }}
    runs-on: ubuntu-latest
    environment: tst

    steps:
    - name: Checkout Code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Bicep Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ../demolake/deploy/infra/main.bicep
        failOnStdErr: false

  deploy-infra-prd:
    if: ${{ github.event.inputs.deploy-target == 'prd' }}
    runs-on: ubuntu-latest
    environment: prd

    steps:
    - name: Checkout Code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Bicep Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ../demolake/deploy/infra/main.bicep
        failOnStdErr: false
